[package]
name = "client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "API version negotiation client for Kubernetes Dynamic Resource Allocation (DRA)"
include = [
    "Cargo.toml",
    "src/**/*",
]
